#!/usr/bin/env sh
# Rebuild the exact OCB distribution with the pinned bearer extension fix.
set -eu

root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
dist="${root}/dist"
module='github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension'
version='v0.150.0'
upstream="$(go env GOMODCACHE)/${module}@${version}"
patched="${dist}/bearertokenauth-patched"
marker="${patched}/.fabric-generated-v0.150.0"

[ -f "${dist}/go.mod" ] || { echo 'OCB distribution has not been generated' >&2; exit 1; }
[ -f "${upstream}/bearertokenauth.go" ] || go mod download "${module}@${version}"
[ -f "${upstream}/bearertokenauth.go" ] || { echo 'pinned bearer module is unavailable' >&2; exit 1; }

# This path is generated by this script only. Refuse to delete any directory
# without its marker so a custom local module cannot be overwritten.
if [ -e "${patched}" ]; then
  [ -f "${marker}" ] || { echo 'refusing to replace unmarked bearer source' >&2; exit 1; }
  rm -rf -- "${patched}"
fi
cp -R "${upstream}" "${patched}"
chmod -R u+w "${patched}"
: >"${marker}"
(
  cd "${patched}"
  git apply --check -p3 "${root}/upstream/bearertokenauth-empty-tokens.patch"
  git apply -p3 "${root}/upstream/bearertokenauth-empty-tokens.patch"
  gofmt -w config.go bearertokenauth.go
  cp "${root}/upstream/bearertokenauth_empty_tokens_test.go" ./bearertokenauth_empty_tokens_test.go
  go test -run '^TestFabric' .
)
(
  cd "${dist}"
  go mod edit "-replace=${module}=./bearertokenauth-patched"
  go build -mod=mod -o otelcol-fabric .
)
# The final binary, not merely the generated go.mod, must name the patched
# local module. A failed assertion aborts both the image and bare build.
go version -m "${dist}/otelcol-fabric" | awk -v module="${module}" '
  $1 == "dep" && $2 == module { want_replace = 1; next }
  want_replace && $1 == "=>" && $2 == "./bearertokenauth-patched" { found = 1; exit }
  want_replace { want_replace = 0 }
  END { exit !found }
'
