header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: "AI5Labs Research OPC Private Limited"
    copyright-year: "2026"
    content: |
      Copyright [year] [owner]
      SPDX-License-Identifier: Apache-2.0
  paths:
    - "**/*.py"
    - "**/*.go"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
  paths-ignore:
    - ".git"
    - "**/node_modules"
    - "**/vendor"
    - "**/__pycache__"
    - "**/*.md"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.json"
    - "**/*.toml"
    - "LICENSE"
    - "NOTICE"
  comment: on-failure
