apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.ports.otlpGrpc }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.service.ports.otlpHttp }}
      targetPort: otlp-http
      protocol: TCP
    - name: health
      port: {{ .Values.service.ports.health }}
      targetPort: health
      protocol: TCP
