#!/usr/bin/env python3
# Copyright 2026 AI5Labs Research OPC Private Limited
# SPDX-License-Identifier: Apache-2.0
"""Print scanner rule/location metadata without source snippets or messages.

This does not change results, suppressions, SARIF uploads or scanner exit codes.
Its input is the SARIF generated by the same CI job, not a remote alert API.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


def result_metadata(document: dict[str, Any]) -> list[dict[str, Any]]:
    records = []
    for run in document["runs"]:
        driver = run["tool"]["driver"]
        rules = {rule["id"]: rule for rule in driver.get("rules", [])}
        for result in run.get("results", []):
            rule_id = result["ruleId"]
            locations = []
            for location in result.get("locations", []):
                physical = location["physicalLocation"]
                locations.append(
                    {
                        "path": physical["artifactLocation"].get("uri"),
                        "line": physical.get("region", {}).get("startLine"),
                    }
                )
            records.append(
                {
                    "tool": driver["name"],
                    "rule_id": rule_id,
                    "level": result.get("level", "warning"),
                    "security_severity": rules.get(rule_id, {})
                    .get("properties", {})
                    .get("security-severity"),
                    "locations": locations,
                }
            )
    return records


def main() -> int:
    files = []
    for argument in sys.argv[1:]:
        path = Path(argument)
        files.extend(sorted(path.glob("*.sarif")) if path.is_dir() else [path])
    if not files:
        raise ValueError("No generated SARIF files supplied")
    for path in files:
        records = result_metadata(json.loads(path.read_text()))
        print(json.dumps({"sarif": path.name, "result_count": len(records)}))
        for record in records:
            print(json.dumps(record))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
