{{- if and (gt (int .Values.replicaCount) 1) .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "presidio-sidecar.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "presidio-sidecar.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "presidio-sidecar.selectorLabels" . | nindent 6 }}
{{- end }}
